### PR TITLE
Home names sanitised

### PR DESCRIPTION
**Pull request by psiber-on-uncovery**
Home names checked using regex to ensure within desired ranges.
Logic check for changes done by comparing sanitised string to raw input, if they don't match, error thrown as requested.

### CODE REVIEW

**Comment by uncovery** [comment]
Looks good, but please do not use CAPS in variables. Could you fix that? (i.e. use $sanitized_name instead of $sanitized_Name).

The rule of thumb is to stick with the existing variable name conventions. Further, the CAPS in names are used to prevent underscores (e.g. $sanitizedNames), using both underscores and CAPS is a bit of overkill :D

**Comment by psiber-on-uncovery** [comment]
no worries. sorted.

**Comment by uncovery** [comment]
thanks! Re-introduced the trim() and put it live on the server now.

**Comment by psiber-on-uncovery** [comment]
You know the trim becomes extraneous right? The reg expression removes all the spaces.

**Comment by uncovery** [comment]
The argument from the command might include a space at the end that the user did not even mean to put there. I don't want the regex to fail because of that and rather pretend that it's not there and remove it.

**Pull request merged**
