### PR TITLE
Update nocheatplus.conf

### PR DESCRIPTION
**Pull request by darthandrew1**
Changed a few settings.

### CODE REVIEW

**Comment by uncovery** [comment]
Sorry, but we have an issue with survivalfly and passable, you change none of them. I would need an explanation how these commands would allow the server to run better and why all users should have these exceptions.

**Comment by darthandrew1** [comment]
I was just putting in a low-level edit, I'm not done yet.

- First edit allows players to see /plugins

- Second restricts /op and /deop to console only (security)

- Third loosens up fastbreak, allowing haste 2 beacon and eff. 5 diamond pick to work correctly

- Fourth allows multiple players to join in the same few seconds

- Fifth allows for the faster flying that was added in 1.8 (pressing ctrl while flying)

**Comment by darthandrew1** [comment]
Besides, there's not much we can change about survivalFly.

**Comment by uncovery** [comment]
- I would not agree to open commands to the whole server without a discussion. Why is this needed?
- fine
- fastbreak is in the logs about 5 times a week, thats one incident a day. I am not sure we need to change that? If you look at the stats the incidents are all from 2014.
- we did not have one single incident of login issues EVER.
- fine

**Comment by uncovery** [comment]
I will make the changes here locally, since its only 2 fields.

**Pull request closed without merging**
