### PR TITLE
Fixed bugs with buy xp command.

### PR DESCRIPTION
**Pull request by psiber-on-uncovery**
Code cleanup, update of structure to make condition checking clearer, removal of unnecessary recalculations of paid value for xp. Fixed bug with values being removed from players accounts - i think.

### CODE REVIEW

**Comment by uncovery** [comment]
Can you make sure the indentations are correct? I did not merge this yet, it looks like its wrong. Every if() { should cause a 4-spaces (not tabs) indent.

**Comment by psiber-on-uncovery** [comment]
Apologies, didn't realise it was yaml style spaced indents.

Should be all fixed, let me know.

**Comment by uncovery** [comment]
Please see my correction for your pull request for future reference: https://github.com/uncovery/uncovery_me/commit/4f3bcdc0e9bceb593f5583e9730483b6c0cc41dd#diff-7470937e95b9cb0f635b6c3a493fe0d8

**Comment by psiber-on-uncovery** [comment]
Ahhhh, wasn't sure if that was the case, so that is excellent to know. 

Keeps the code lovely and clean, i like.

**Comment by uncovery** [comment]
Yeah I figured that if we encounter an error, we might as well stop running the script.

**Comment by uncovery** [comment]
Original text from Sleeping: "In kingdom lots that have transferred ownership since our 1.8 upgrade players cannot activate buttons, levers, or pressure plates without permission on the lot.  I had noticed for some time that on some lots players could use them and on some lots players could not use them and finally realized it is when a lot transfers ownership that they lose the right."

**Comment by uncovery** [comment]
I asked him to show me a lot where this is the case and a player who cannot use them so I can debug. There is a detailed permissions debug mode where I get spammed with every single permission check in the console to find out where it's being denied and by what plugin. So I am waiting for that and then we see.

**Pull request merged**
